name: Deploy Images to GHCR

on:
  push:
    branches:
      - master
      - feature/ci-cd

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/retraut/spot-termination-exporter:${GITHUB_SHA}
          docker push ghcr.io/retraut/spot-termination-exporter:${GITHUB_SHA}
